### ISSUE TITLE
Rainbowfrog x Haddaway

### ISSUE THREAD

**Issue by cpeddecord** [cpeddecord/rainbowfrog#6]
as a user of rainbowfrog I would like to have his likeness synced to Haddaway's "What is Love."

https://www.youtube.com/watch?v=HEXWRTEbj1I

**Comment by cpeddecord** [comment]
@jquatier @zacparker @seanohollaren @JasonVeselka 

If we could get some comments on this, let me know what you think.

**Comment by zacparker** [comment]
:+1:

**Comment by jquatier** [comment]
I'm honestly surprised / appalled this hasn't been done already, given the popularity of both. Seems like it should be easy enough to time the right frames of the animation to the BPM of the track. Since it involves animation, we may need to consult with @JasonVeselka, although I know he's been busy with #5 .
